### ISSUE TITLE
Node engine version

### ISSUE THREAD

**Issue by jimschubert** [sandro-pasquali/autopilot#1]
On OS X, package installation fails for 0.11.x versions but succeeds for 0.10.20+ and 0.12.0.

I'd consider limiting the node engine in package.json:

```
  "engines": { "node" : ">=0.12.0" },
  "engineStrict": true,
```

**Comment by sandro-pasquali** [comment]
That's a good suggestion. I'll add an "engines" definition.

"engineStrict" is deprecated. I'm not sure what will replace it, if anything, in npm 3.
